version: "3"
services:
  vendor-portal:
    image: mane/selenium-docker
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: mane/selenium-docker
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/vendor-flight-reservation:/home/selenium-docker/test-output
